using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using RealTimeCharts_Server.DataStorage;
using RealTimeCharts_Server.HubConfig;
using RealTimeCharts_Server.TimerFeatures;

namespace RealTimeCharts_Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ChartController : ControllerBase
    {
        private readonly IHubContext<ChartHub> _chartHub;

        public ChartController(IHubContext<ChartHub> chartHub)
        {
            _chartHub = chartHub;
        }

        public IActionResult Get()
        {
            var timerManager = new TimerManager(() =>
                // we are sending generated data to all subscribed clients 
                // on the transferchartdata event. This means that every client if it has a listener 
                // on the transferchartdata event, will receive a data generated by the DataManager class. 
                // And that is exactly what we are going to do in the next section
                _chartHub.Clients.All.SendAsync("transferchartdata", DataManager.GetData())
            );

            return Ok(new { Message = "Request Completed" });
        }
    }
}